services:
  # Frontend & Router (Host Port 8080 -> Container Port 80)
  frontend:
    build: ./frontend
    container_name: yts-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

  # Flask API (Internal Port 5000)
  backend:
    build: ./backend
    container_name: yts-backend
    restart: always
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    environment:
      # FORCE Google to allow internal HTTP traffic behind Nginx
      - OAUTHLIB_INSECURE_TRANSPORT=1
    depends_on:
      - redis

  # Celery Worker (Background Tasks)
  worker:
    build: ./backend
    container_name: yts-worker
    restart: always
    command: celery -A app.celery worker --loglevel=info
    # This loads all variables (including Webshare ones) automatically
    env_file:
      - ./backend/.env
    environment:
      # FORCE Google to allow internal HTTP traffic here too
      - OAUTHLIB_INSECURE_TRANSPORT=1
    depends_on:
      - redis
      - backend

  # Redis (Cache & Sessions)
  redis:
    image: "redis:alpine"
    container_name: yts-redis
    restart: always
    expose:
      - "6379"